export const adminIds = ["116169166248811888379"];

export const initialTags = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "DevOps Engineer",
  "Quality Assurance Engineer",
  "UX Designer",
  "Product Manager",
  "Data Scientist",
  "Operations Manager",
  "Supply Chain Manager",
  "Network Administrator",
  "Database Administrator",
  "Full Stack Developer",
];

export const FilterData = [
  {id: "1", label: "Software Engineer", value: "software_engineer"},
  {id: "2", label: "Frontend Developer", value: "frontend_developer"},
  {id: "3", label: "Backend Developer", value: "backend_developer"},
  {id: "4", label: "DevOps Engineer", value: "devops_engineer"},
  {id: "5", label: "Quality Assurance Engineer", value: "qa_engineer"},
  {id: "6", label: "UX Designer", value: "ux_designer"},
  {id: "7", label: "Product Manager", value: "product_manager"},
  {id: "8", label: "Data Scientist", value: "data_scientist"},
  {id: "9", label: "Operations Manager", value: "operations_manager"},
  {id: "10", label: "Supply Chain Manager", value: "supply_chain_manager"},
  {id: "11", label: "Network Administrator", value: "network_administrator"},
  {id: "12", label: "Database Administrator", value: "database_administrator"},
  {id: "13", label: "Full Stack Developer", value: "full_stack_developer"},
  {id: "14", label: "Frontend Developer (React)", value: "frontend_react"},
  {id: "15", label: "Frontend Developer (Vue)", value: "frontend_vue"},
  {id: "16", label: "Frontend Developer (Angular)", value: "frontend_angular"},
  {id: "17", label: "Mobile Developer (React Native)", value: "mobile_react_native"},
  {id: "18", label: "Mobile Developer (Flutter)", value: "mobile_flutter"},
  {id: "19", label: "Data Engineer", value: "data_engineer"},
  {id: "20", label: "Machine Learning Engineer", value: "ml_engineer"},
];
